//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin_tb()
        {
            this.CATEGORies = new HashSet<CATEGORY>();
        }
    
        public int ADMIN_ID { get; set; }

        [Required(ErrorMessage ="Admin Name is Required")]
        [Display(Name ="Admin Name")]
        public string ADMIN_NAME { get; set; }

        [Required(ErrorMessage = "Admin Password is Required")]
        [Display(Name = "Admin Password")]
        [DataType(DataType.Password)]
        public string ADMIN_PASSWORD { get; set; }

        [Required(ErrorMessage = "Confirm Password is Required")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("ADMIN_PASSWORD",ErrorMessage ="Password not equal")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Email is Required")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORY> CATEGORies { get; set; }
    }
}
