//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.QUESTIONS = new HashSet<QUESTION>();
        }
    
        public int CAT_ID { get; set; }

        [Required(ErrorMessage = "Subject Name is Required")]
        [Display(Name = "Subject")]
        public string CAT_NAME { get; set; }
        public Nullable<int> CAT_ADMIN_ID { get; set; }
        public string cat_encrypted_string { get; set; }
    
        public virtual Admin_tb Admin_tb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTION> QUESTIONS { get; set; }
    }
}
