//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public int QUE_ID { get; set; }

        [Required(ErrorMessage = "Question field is Required")]
        [Display(Name = "Question")]
        public string QUE_TEXT { get; set; }

        [Required(ErrorMessage = "field A is Required")]
        [Display(Name = "A")]
        public string OPT_A { get; set; }

        [Required(ErrorMessage = "field A is Required")]
        [Display(Name = "B")]
        public string OPT_B { get; set; }

        [Required(ErrorMessage = "field A is Required")]
        [Display(Name = "C")]
        public string OPT_C { get; set; }

        [Required(ErrorMessage = "field A is Required")]
        [Display(Name = "D")]
        public string OPT_D { get; set; }

        [Required(ErrorMessage = "field A is Required")]
        [Display(Name = "Correct Option")]
        public string CORRECT_OPT { get; set; }
        public Nullable<int> QUE_CAT_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
